# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OrderManagement.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15OrderManagement.proto\x12\tordermgmt\x1a\x1egoogle/protobuf/wrappers.proto\"[\n\x05Order\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05items\x18\x02 \x03(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x02\x12\x13\n\x0b\x64\x65stination\x18\x05 \x01(\t\"T\n\x10\x43ombinedShipment\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12$\n\nordersList\x18\x03 \x03(\x0b\x32\x10.ordermgmt.Order2\xdd\x02\n\x0fOrderManagement\x12:\n\x08\x61\x64\x64Order\x12\x10.ordermgmt.Order\x1a\x1c.google.protobuf.StringValue\x12:\n\x08getOrder\x12\x1c.google.protobuf.StringValue\x1a\x10.ordermgmt.Order\x12@\n\x0csearchOrders\x12\x1c.google.protobuf.StringValue\x1a\x10.ordermgmt.Order0\x01\x12@\n\x0cupdateOrders\x12\x10.ordermgmt.Order\x1a\x1c.google.protobuf.StringValue(\x01\x12N\n\rprocessOrders\x12\x1c.google.protobuf.StringValue\x1a\x1b.ordermgmt.CombinedShipment(\x01\x30\x01\x62\x06proto3')



_ORDER = DESCRIPTOR.message_types_by_name['Order']
_COMBINEDSHIPMENT = DESCRIPTOR.message_types_by_name['CombinedShipment']
Order = _reflection.GeneratedProtocolMessageType('Order', (_message.Message,), {
  'DESCRIPTOR' : _ORDER,
  '__module__' : 'OrderManagement_pb2'
  # @@protoc_insertion_point(class_scope:ordermgmt.Order)
  })
_sym_db.RegisterMessage(Order)

CombinedShipment = _reflection.GeneratedProtocolMessageType('CombinedShipment', (_message.Message,), {
  'DESCRIPTOR' : _COMBINEDSHIPMENT,
  '__module__' : 'OrderManagement_pb2'
  # @@protoc_insertion_point(class_scope:ordermgmt.CombinedShipment)
  })
_sym_db.RegisterMessage(CombinedShipment)

_ORDERMANAGEMENT = DESCRIPTOR.services_by_name['OrderManagement']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ORDER._serialized_start=68
  _ORDER._serialized_end=159
  _COMBINEDSHIPMENT._serialized_start=161
  _COMBINEDSHIPMENT._serialized_end=245
  _ORDERMANAGEMENT._serialized_start=248
  _ORDERMANAGEMENT._serialized_end=597
# @@protoc_insertion_point(module_scope)
