# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProductInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11ProductInfo.proto\x12\x08\x65\x63omerce\x1a\x1egoogle/protobuf/wrappers.proto\"\x1a\n\tProductID\x12\r\n\x05value\x18\x01 \x01(\t\"G\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x02\x32y\n\x0bProductInfo\x12\x34\n\naddProduct\x12\x11.ecomerce.Product\x1a\x13.ecomerce.ProductID\x12\x34\n\ngetProduct\x12\x13.ecomerce.ProductID\x1a\x11.ecomerce.Productb\x06proto3')



_PRODUCTID = DESCRIPTOR.message_types_by_name['ProductID']
_PRODUCT = DESCRIPTOR.message_types_by_name['Product']
ProductID = _reflection.GeneratedProtocolMessageType('ProductID', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTID,
  '__module__' : 'ProductInfo_pb2'
  # @@protoc_insertion_point(class_scope:ecomerce.ProductID)
  })
_sym_db.RegisterMessage(ProductID)

Product = _reflection.GeneratedProtocolMessageType('Product', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCT,
  '__module__' : 'ProductInfo_pb2'
  # @@protoc_insertion_point(class_scope:ecomerce.Product)
  })
_sym_db.RegisterMessage(Product)

_PRODUCTINFO = DESCRIPTOR.services_by_name['ProductInfo']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PRODUCTID._serialized_start=63
  _PRODUCTID._serialized_end=89
  _PRODUCT._serialized_start=91
  _PRODUCT._serialized_end=162
  _PRODUCTINFO._serialized_start=164
  _PRODUCTINFO._serialized_end=285
# @@protoc_insertion_point(module_scope)
